[package]
name = "var_provider"
version = "0.4.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
itertools = "0.14"
strum = "0.27"
strum_macros = "0.27"
crossterm = "0.29"
textwrap = "0.16"
